version: '3'

services: 

  app:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: financial-balance-web
    ports: 
      - "8080:8080"
    networks: 
      - financial-app-network

networks: 
  financial-app-network:
    driver: bridge