version: '3'

services: 

  web:
    build:
      dockerfile: Dockerfile
      context: .
    image: marcelofelixsalgado/financial-web
    container_name: financial-web
    entrypoint: /financial-web
    ports: 
      - "8080:8080"
    networks: 
      - financial-network

networks: 
  financial-network:
    name: financial-network
    driver: bridge